### ISSUE TITLE
Format of the date stored is not consistent

### ISSUE THREAD

**Issue by weikangchia** [CS2103AUG2016-F10-C1/main#10]
![fix date format](https://cloud.githubusercontent.com/assets/2174882/19138339/c0a631a0-8bad-11e6-8044-223ec672fcd6.png)

**Comment by jaeoheeail** [comment]
Is it because of the way you keyed in? 

Check the method that cuts up the string and store the dates

**Comment by jaeoheeail** [comment]
Oh the issue is closed hahaha

**Comment by johnervan** [comment]
@jaeoheeail yeah just needed to format the datetime object before you store it as a string
