### ISSUE TITLE
Fix GUI Tests

### ISSUE THREAD

**Issue by jaeoheeail** [CS2103AUG2016-F10-C1/main#14]

**Comment by jaeoheeail** [comment]
<img width="360" alt="screen shot 2016-10-06 at 11 02 15 pm" src="https://cloud.githubusercontent.com/assets/12406588/19158075/048b8782-8c1a-11e6-8b01-0b95ba47e740.png">

**Comment by johnervan** [comment]
@jaeoheeail good job!
