### ISSUE TITLE
Mark your code with special tag @@author

### ISSUE THREAD

**Issue by weikangchia** [CS2103AUG2016-F10-C1/main#62]
" Mark your code with special tag @@author so that we can extract code written by each of you using the collate tool (for evaluation purposes). After that, Use the collate tool to extract individual code and look through the generated .md files to ensure all your code has been extracted correctly. Push the *.md files created to a folder called /collated in your repo. "

**Comment by jaeoheeail** [comment]
Okay will do! We do this on Develop?

**Comment by weikangchia** [comment]
Yup we can write on develop, we should start soon cos we may forget what we have wrote later.

**Comment by johnervan** [comment]
ok sure!
